[package]
name = "pjsk-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pjsk-core = { path = "../pjsk-core" }
pjsk-assets = { path = "../pjsk-assets" }
pjsk-live2d = { path = "../pjsk-live2d" }
pjsk-ugui = { path = "../pjsk-ugui" }
pjsk-text = { path = "../pjsk-text" }

[lints]
workspace = true
