[package]
name = "pjsk-bake"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pjsk-core = { path = "../pjsk-core" }
pjsk-ir = { path = "../pjsk-ir" }
pjsk-assets = { path = "../pjsk-assets" }
pjsk-timeline = { path = "../pjsk-timeline" }
pjsk-live2d = { path = "../pjsk-live2d" }
pjsk-ugui = { path = "../pjsk-ugui" }
pjsk-text = { path = "../pjsk-text" }

[lints]
workspace = true
